Feature #7 공지 페이지 구현
LikeLion-at-DGU/2024_fall_festival_front pull request #19
Opened 2024-09-22 10:11 UTC by gn00py48

## 🔍 What is the PR?

- API 연결 제외 공지 페이지 구현 되었습니다.
- react modal 라이브러리 사용했습니다. 문제 시 삭제 후 다시 없이 구현하겠습니다.
- 인스타그램 아이콘 svg 로 수정할 예정입니다.

## 📸 Screenshot

![image](https://github.com/user-attachments/assets/00f50b4f-e0b0-4d80-80bf-98e36343015a)
![image](https://github.com/user-attachments/assets/a3756966-fda6-4515-8e70-3133dd169662)

## 📍 PR Point

## 📢 Notices

- 목업 더미데이터 넣어뒀습니다. 추후 API 연결 후 대체하겠습니다.
- react modal 라이브러리 사용했습니다.

## ✅ Check List

- [ ] Merge 하는 브랜치가 올바른가?
- [ ] PR과 관련없는 변경사항이 없는가?
- [ ] 내 코드에 대한 자기 검토가 되었는가?

## 💭 Related Issues

- 공지페이지
- #7

2024-09-22 14:46 UTC, Chaem03 requested changes

2024-09-22 14:46 UTC, Chaem03 commented on src/components/notice/MainNotice/MainStyle.js
폰트 적용은 아마 노션에 적힌 폰트 적용 코드대로 해주셔야 적용됩니다..! 노션 확인 후 폰트 적용 확인해주세요! 수고하셨습니다:)

2024-09-23 10:35 UTC, gn00py48 reviewed
폰트 적용 방법 노션 기입 방식으로 진행했습니다!
이게 아니라면... 다시 수정하겠습니다 😵‍💫😭

2024-09-24 05:25 UTC, Minn-Choi commented
확인했습니다 ! 폰트 적용 방법도 확인했습니다 !

2024-09-24 05:28 UTC, Chaem03 approved these changes

2024-09-24 07:46 UTC, merged